### ISSUE TITLE
Windows Defender detecting a Trojan

### ISSUE THREAD

**Issue by Nogloon** [RimSort/RimSort#132]
Please advise, is this a false positive?
![image](https://github.com/RimSort/RimSort/assets/85416691/9960f73d-b8ae-45ee-8b86-be39f78b834c)

**Comment by Chunnyluny** [comment]
this is a case of false positive. Your windows defender/other anti-virus programs will flag RimSort, because it is so new, it has not much knowledge from users. Don't worry about it. it is open source and there are no malicious files in this project. The project is progressing fast and I hope you will see its advantages soon. everybody is working hard on the project and note: people that seem to be sus don't put everything open for the public. you can whitelist RimSort so it won't be put in quarantaine anymore.

**Comment by twstagg** [comment]
@Nogloon Extending off of what @Chunnyluny said, this is definitely a false positive. We use Nuitka to compile the application into the executable you get from releases.

You are more than welcome to take a look at the [Development Guide](https://github.com/RimSort/RimSort/wiki/Development-Guide) and build yourself - from there you will observe that the issue is present even for builds that you create yourself.

Windows users will need to add an exception in their AV program.
