### ISSUE TITLE
Suggestion: Notify user only when a new update is available

### ISSUE THREAD

**Issue by Limfjorden** [RimSort/RimSort#183]
When opening Rimsort, a popup window appears telling me that my app is up to date. This is because I have it set to check for updates I imagine.

It would be better if it only notified me if there was actually an update available to download. It's a minor annoyance, but nothing too difficult to change (I hope).

It should go without saying that this is not a high priority issue, it's just a minor annoyance.

**Comment by twstagg** [comment]
> When opening Rimsort, a popup window appears telling me that my app is up to date. This is because I have it set to check for updates I imagine.
> 

Apologies for the confusion. I did make this enabled by default. There is a checkbox you can use to turn this behavior off:

[Screencast from 2023-10-10 17-34-02.webm](https://github.com/RimSort/RimSort/assets/2766946/b768d83c-4e0a-4ca5-a612-a1c14e094231)

> It would be better if it only notified me if there was actually an update available to download. It's a minor annoyance, but nothing too difficult to change (I hope).
> 
> It should go without saying that this is not a high priority issue, it's just a minor annoyance.

See the above video for how to resolve. I am going to make this option not a default option. Humbly, I enabled this "right-click button" nonsense out of my own laziness. That will be improved upon in the future.

Fixed in a671df9
