### ISSUE TITLE
Implement texture compression/conversion utilities

### ISSUE THREAD

**Issue by twstagg** [RimSort/RimSort#24]
If we follow in RimPy's footsteps, we would probably need to implement some sort of threading util eventually, so that we can add an "Optimize tex" option like RimPy:

- This is what RimPy uses for the bulk of what it does for CPU based texture conversion with what appears to be multi-threaded processes in python
    - bc7enc
        - https://github.com/richgel999/bc7enc_rdo
            - Linux
            - Mac
            - Windows
- This is what RimPy uses for GPU based texture conversion on Windows:
    - texconv
        - https://github.com/Microsoft/DirectXTex/wiki/Texconv
            - `C:\Users----\Documents\RimPy\compressors\texconv.exe"  "C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2842502659\Textures\Abilities\Warlord\AdrenalineRush.png" -f BC7_UNORM -y -vflip -fixbc4x4 -m 1 -o "C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2842502659\Textures\Abilities\Warlord`
    - ![image](https://user-images.githubusercontent.com/2766946/220246389-04bc3fb9-49a2-44a4-b8ae-79837b7cf37b.png)
    - ![image](https://user-images.githubusercontent.com/2766946/220241768-1da0ff77-b669-4952-af6b-60fbb6281889.png)

Alternative option(s):
- Bradson's alternative: https://github.com/bbradson/DDSgenerator
- Bradson also showed me this: 
    - https://github.com/joseasoler/png2dds/wiki/Example:-RimWorld
    - [10:40 AM]Bradson: This is another C++ tool jose put up in dub's discord's fixlist. It's based on bc7enc too and uses the same args, but does the job faster than rimpy with its python limitations
    - Rather than threading it ourselves, we could just call png2dds by itself and allow it to do its thing.

**Comment by joseasoler** [comment]
Hello! I am the developer of png2dds. I have been investigating texture encoding for RimWorld for a while; here are some extra bits of info that may be helpful.

* png2dds is also CPU based. Since it is based on bc7enc, the resulting encoded images have a higher level of quality than the alternatives.

* bc7enc and png2dds lack mipmap support, which is currently only present in texconv. I am currently working on adding this feature to png2dds.

* png2dds is between 2 and 3 faster than texconv and bc7enc for encoding RimWorld textures. This is because png2dds handles all files at once using the same multithreaded pipeline. Other alternatives must stop to read and write files, but png2dds can read and write at the same time it is encoding other files.

* [NVIDIA Texture Tools 3](https://developer.nvidia.com/gpu-accelerated-texture-compression) is a cross-platform GPU encoder. Unfortunately, it does not support Mac. I do not know if its license allows redistributing the tool with other software.

You can find my analysis comparing these four tools here: https://github.com/joseasoler/png2dds/wiki/Performance

I am obviously biased, but I think that png2dds is a great option. One of my goals with png2dds is integrating it with mod managers to let the community benefit from it. I am open to implementing features that make integration easier :)

**Comment by twstagg** [comment]
> Hello! I am the developer of png2dds. I have been investigating texture encoding for RimWorld for a while; here are some extra bits of info that may be helpful.
> 
>     * png2dds is also CPU based. Since it is based on bc7enc, the resulting encoded images have a higher level of quality than the alternatives.
> 
>     * bc7enc and png2dds lack mipmap support, which is currently only present in texconv. I am currently working on adding this feature to png2dds.
> 
>     * png2dds is between 2 and 3 faster than texconv and bc7enc for encoding RimWorld textures. This is because png2dds handles all files at once using the same multithreaded pipeline. Other alternatives must stop to read and write files, but png2dds can read and write at the same time it is encoding other files.
> 
>     * [NVIDIA Texture Tools 3](https://developer.nvidia.com/gpu-accelerated-texture-compression) is a cross-platform GPU encoder. Unfortunately, it does not support Mac. I do not know if its license allows redistributing the tool with other software.
> 
> 
> You can find my analysis comparing these four tools here: https://github.com/joseasoler/png2dds/wiki/Performance
> 
> I am obviously biased, but I think that png2dds is a great option. One of my goals with png2dds is integrating it with mod managers to let the community benefit from it. I am open to implementing features that make integration easier :)

Hey there @joseasoler !

Well met! I really appreciate the info! @oceancabbage and I are always looking for contributors, so feel free to make any changes you like and submit a PR! The more the merrier!

I think that png2dds is what we will be doing for the cross platform CPU encoding for sure. Thanks for providing that NVIDIA link as well. Even if we can't GPU encode on Mac (this might even be optimal on most Apple hardwares...) it is still AWESOME to have some options for Linux/Windows platforms. I will definitely be taking a look at that.

Please join us at #rimsort-testing channel on the Rocketman + CAI Discord server - that is where we are hanging out for the time being. We would love to hear your thoughts! :)

**Comment by twstagg** [comment]
todds is integrated fully into RimSort now!
