### ISSUE TITLE
FIXME: Updater does not update mods

### ISSUE THREAD

**Issue by thekalbb** [RimSort/RimSort#277]
**Describe the bug**
When i use the mod updater, 
Select the mod i want to update
Press "Update Mods"
Mouse changes to the "thinking/working" mousepointer
But nothing happens

**To Reproduce**
Same as above, happenes 100% of the time.

![billede](https://github.com/RimSort/RimSort/assets/20153559/01e89100-3e43-4066-b298-397ae466de99)

Everything looks fine to me in the settings
![billede](https://github.com/RimSort/RimSort/assets/20153559/d867f5cc-92c0-4737-89e3-029b21409d9d)

**Comment by GitWolf22k** [comment]
Same issue, even after deleting steamcmd folder & re-running steamcmd setup.

**Comment by LionelColaso** [comment]
> Same issue, even after deleting steamcmd folder & re-running steamcmd setup.

make sure you using edge version of RimSort and setup steamcmd through settings not from the main tab it sthould fix your issue

**Comment by twstagg** [comment]
Probably unsubscribe and resubscribe from the problematic mods. This could be an issue with Steam Workshop as well.

**Comment by King-of-Blades** [comment]
Also still experiencing this on the edge build even after a complete reinstall of both rimsort and steamcmd.

**Comment by NeveHanter** [comment]
I have similar issues with current git master on Linux, after mod update from RimSort I'm "losing" some of the mods, get notifications about duplicates and when I click show details there's only Invalid item entry that I can also see on the inactive/active lists in the main window. RimSort is using Steam through SteamAPI for all of these operations.

Example:
RimSort displays update mods pop-up, I select River's Tribal Shoes from the list and hit update mods, RimSort logs the following:
```
(rimsort) [nevehanter@cobaltblue rimsort]$ python -m app
[S_API] SteamAPI_Init(): Loaded '/home/nevehanter/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 294100
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197999718654 [API loaded no]
```
Steam starts doing "sth", it takes ~5-10s, then I hit refresh in RimSort and I'm being greeted with
![image](https://github.com/RimSort/RimSort/assets/3267401/0a3a9144-7fd1-4a65-a8e4-7d2ed3d2e8bb).
It seems it only managed to unsubscribe the mod.

When I do this for all the mods that need updating then from time to time (not always) I'm getting duplicate error and an Invalid item (leftover .DDS textures?).

Also, this time clicking download with Steam in missing mods pop-up worked, but sometimes it doesn't work, i.e. I click it, wait for steam to finish what it started doing, click refresh and see that RimSort still wants to download all or some of these mods.

**Comment by twstagg** [comment]
Hi. This issue should be better now. I've changed the amount of api calls I do for unsub actions, and I have verified that I can see the proper callbacks on Windows 11 and Ubuntu 24.04 at least. Can you guys please try again with the latest Edge release?

Also, one thing I notice is that contrary to the experience you might have when you go to a workshop mod page in steam client and unsub / resub, Steam does not seem to begin immediately removing or downloading a mod respectively, until an appid update or validation task is triggered in the steam client. This is why I tried to have it do Unsub twice in a row, because sometimes that seemed to make it delete the mod immediately following the api calls. But that was causing other issues, so i disabled that behavior.

To help mitigate this, I was automatically doing it after unsub / resub api calls, but now I have removed that from the process that happens with the steamworks api calls, and there is now a Help -> Validate Steam client mods option in the top menu bar.

Please let me know what you guys experience with it.

**Comment by ArsenalHail** [comment]
Still getting the same issues even after switching to the edge version with the previous push. I'm running on windows 10, is it supported on there? Basically no mods get updated, and when i save and run, no mods are loaded into the game. Lemme know if theres any more information i should give.

**Comment by hk21702** [comment]
@ArsenalHail the mods not loading into the game are a separate issue, so please make a different issue for that

As for the mod updates, what kind of mod are you trying to update? steam workshop mods? steamcmd mods? if the former, do you have steam running and logged in with the account that has rimworld? do you have steam integration enabled in rimsort? sometimes steam needs a kick to get mods to update and you'll need to validate mod files. All rimsort is doing in the case of workshop mods is sending api signals to the steam client to handle the update itself.
