### ISSUE TITLE
FIXME: Application not responding for several seconds after initial load

### ISSUE THREAD

**Issue by divineDerivative** [RimSort/RimSort#300]
**Describe the bug**
After opening RimSort, the application starts normally. I can move the window around while it loads the mods. I get the duplicate mod ID warning and after closing that, I am unable to interact with the window for several seconds. Trying to move the window or click on anything just does nothing. Trying repeatedly will eventually trigger the (Not Responding) notice at the top. Once it starts responding, if I had tried to move the window, then the window will move. If I had tried to click on a specific mod, that mod will be selected.
**To Reproduce**
Open RimSort and after dismissing any warnings try to click on anything or move the window.
**Expected behavior**
If the application is not finished initializing, there should be some indication so users do not think it has frozen.

**Screenshots**
![Screenshot 2024-04-21 141326](https://github.com/RimSort/RimSort/assets/78392890/7b64de14-3c1e-494d-b6a9-1f6ea61cf4d2)

**Please complete the following information:**
 - OS: Windows 10
 - RimSort version: Alpha-v1.0.6.2-hf [Edge 794a20f]
 - Please provide a `RimSort.log`: https://0x0.st/Xo6U.log
 - Are you running from Python interpreter or from a compiled RimSort release? Compiled Edge release

**Comment by twstagg** [comment]
Hi @divineDerivative ,

I have implemented the native `Observer` via watchdog in 1d4ec36 which is present in the latest Edge release. Can you please test and confirm if this helps?

We had switched to `PollingObserver` on Windows previously due to bugs back when we were on Py3.9 and probably older version of watchdog. I have heard good results on this change from @LionelColaso testing  as well, and would love it if you could confirm resolution.

**Comment by divineDerivative** [comment]
This has been fixed, thank you!
