### ISSUE TITLE
FIXME: Optimize Textures preset not changing

### ISSUE THREAD

**Issue by lukachukai1** [RimSort/RimSort#307]
**Describe the bug**
In the settings, you can change the optimization preset for TODDS optimization, but it reverts right back no matter what. 

**To Reproduce**
1. Go to 'settings'
2. Click on 'quality preset'
3. Select either 'high' or 'low'
4. Return and click "Optimize Textures"

**Expected behavior**
TODDS would use a different preset for optimization
**Screenshots**
![image](https://github.com/RimSort/RimSort/assets/102724357/79d78785-e341-4a98-b962-d05584a99925)
![image](https://github.com/RimSort/RimSort/assets/102724357/2b09e1d7-10c3-44ae-a6a9-ddc4a236519b)

**Please complete the following information:**
 - OS: Windows
 - RimSort version: Alpha-v1.0.6.2-hf
 - Please provide a `RimSort.log`: http://0x0.st/XHmd.log
 - Are you running from Python interpreter or from a compiled RimSort release? - Compiled Release

**Additional context**

**Comment by twstagg** [comment]
Hi @lukachukai1 ,

Please use the Edge pre-release and NOT the Alpha release. Alpha is dated. Development is happening so that we can make a new "stable" release instead of Alpha. For now, please use Edge to get the latest and greatest RimSort code. Closing as this is not pertinent to current version. Please reopen if you experience this issue on current version.

**Comment by lukachukai1** [comment]
good to know!
I didn't realise that the edge pre-release was a thing, because the alpha never detected an update! thanks!
