### ISSUE TITLE
FIXME: scrolling the inactive mods list maxes out a single thread

### ISSUE THREAD

**Issue by cebarks** [RimSort/RimSort#325]
**Describe the bug**
Scrolling the inactive mods list maxes out a single thread

**To Reproduce**
1. Have a decent number of mods in your inactive mods list.
2. Scroll either with your mouse wheel or by clicking and dragging, the ui becomes jumpy and you can observe in your system resource monitor of choice a spike in cpu usage by RimSort maxing out a single thread.

**Expected behavior**
Scrolling is smooth and doesn't max cpu usage.

**Screenshots**
N/A

**Please complete the following information:**
 - OS: Fedora Linux 40 (KDE Plasma) x86_64 (Kernel 6.8.9)
 - RimSort version: Edge af0eae1
 - Please provide a `RimSort.log`: n/a
 - Are you running from Python interpreter or from a compiled RimSort release? linux compiled release

**Additional context**
No errors occur, just laggy UI.

**Comment by twstagg** [comment]
> **Describe the bug** Scrolling the inactive mods list maxes out a single thread
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Have a decent number of mods in your inactive mods list.
> 
>     2. Scroll either with your mouse wheel or by clicking and dragging, the ui becomes jumpy and you can observe in your system resource monitor of choice a spike in cpu usage by RimSort maxing out a single thread.
> 
> 
> **Expected behavior** Scrolling is smooth and doesn't max cpu usage.
> 
> **Screenshots** N/A
> 
> **Please complete the following information:**
> 
>     * OS: Fedora Linux 40 (KDE Plasma) x86_64 (Kernel 6.8.9)
> 
>     * RimSort version: Edge [af0eae1](https://github.com/RimSort/RimSort/commit/af0eae1cc76efd11cf193057a04ebf0efd670282)
> 
>     * Please provide a `RimSort.log`: n/a
> 
>     * Are you running from Python interpreter or from a compiled RimSort release? linux compiled release
> 
> 
> **Additional context** No errors occur, just laggy UI.

Hi. This is not a bug and is intended behavior. We previously loaded all of the widgets at once upon initialization / refresh, but now we lazy load widgets. This is because with more mods, RimSort will completely choke on itself trying to load more than a few thousand mods.

In order to support larger amounts of mods, the mod list item widgets are now lazy loaded. This means that the widget is only created for the item upon the item becoming visible to the user within the list. PySide6 is very limited with the QListWidget class, so I am open to other implementations that are better suited for larger sets of items. If you're scrolling through lots of items, this can temporarily use up a decent amount of resources. This saves time loading the app, and overall gives a better experience with large amounts of items. Once the widgets are loaded, they are there until they are destroyed.
