### ISSUE TITLE
FIXME: Active mod switching to outdated version

### ISSUE THREAD

**Issue by dvn-crtr** [RimSort/RimSort#394]
**Describe the bug:**
When two versions of a mod with the same packageID are installed it seems to default back to the smallest integer in the steam workshop path instead of keeping the right one active. 

**To Reproduce:**

1. Have a non- 1.5 version of a steam workshop mod and an updated fork subscribed.
2. Activate the forked version.
3. Refresh or relaunch RimSort.

**Expected behavior:**
RimSort should ensure the right mod is kept active using the path instead of just the packageID.

**Screenshots:**

**Please complete the following information:**

- RimSort version: 1.0.8
- Are you running from Python interpreter or from a compiled RimSort release? Release.

**Additional context:**
While it's possible to just unsubscribe from the mods that are outdated and only keep the forks subscribed some of the forks are only being maintained while the original mod author is too busy to update their mod for 1.5 so I'd like to keep them subscribed to know when the original is updated to switch back.

**Did you first check the wiki for a solution? (macOS Gatekeeper workaround is there)**
Yeah, I didn't find anything in there regarding this.

**Comment by hk21702** [comment]
Unfortunately, this is more so a limitation of how RimWorld itself handles mods. What RimWorld does is that it has a xml file with the list of active packageIDs. If a packageID is not unique within the user's downloaded mods, then it defaults to the described behavior. There is no picking or choosing. The only solution would be to move the unwanted mod manually out of your mods folder so that RimWorld doesn't detect both.

For RimSort to resolve that and do it for you would require quite an overhaul, so it likely is not going to happen.

**Comment by dvn-crtr** [comment]
how could tynan do this to me D:

at least when loading the game it appears to favor the versions that are valid for 1.5 instead of the one with the lowest steam workshop ID

**Comment by hk21702** [comment]
The wiki claims that it just favors the first one. https://rimworldwiki.com/wiki/Modding_Tutorials/About.xml

Will be closing issue as there isn't really much we can do about it.
