### ISSUE TITLE
FIXME: Infinite Loading bug

### ISSUE THREAD

**Issue by RavePirate** [RimSort/RimSort#428]
**Describe the bug:**
Infinite loading bug on game start when using a modlist with a missing mod

**To Reproduce:**

1. Follow instructions on this collection: https://steamcommunity.com/sharedfiles/filedetails/?id=3254701935
2. Get to importing mod list
3. Import modlist, recieve error of missing mod, press ok
4. Sort Modlist
5. Save
6. Start Game
7. Game will hang on load forever

**Expected behavior:**
RimSort should allow skipping of this mod(s), and load game as normal

**Screenshots:**
![image](https://github.com/RimSort/RimSort/assets/173309271/62af7cc9-f974-4933-b5b3-29ebcdad7c52)

**Please complete the following information:**

- OS: Windows
- RimSort version:1.0.8
- Please provide a `RimSort.log`: https://0x0.st/XTpS.log
- Are you running from Python interpreter or from a compiled RimSort release? Compiled release

**Additional context:**
n/a

**Did you first check the wiki for a solution? (macOS Gatekeeper workaround is there)** Yes

**Comment by Raizanad** [comment]
I'm fairly certain your mod list is the cause of the problem, as even using a collection that would lead you to have missing mods is a poor practice. In rimsort once you save a mod list with missing mods, or sort it, the game will start just fine.

**Comment by hk21702** [comment]
So the skipping of mods would require for rimsort to modify the mod list that RimWorld uses to remove those mods. However, this is dangerous for as it is an extra change to the mod list that the user does not explicitly make. It's something that can cause confusion down the line. 

The hanging of RimWorld itself doesn't have to do with RimSort and is due to those mods with missing data that you see. You will just need to move the problematic mods from the active to the inactive panel.
