### ISSUE TITLE
FIXME: When creating a rule, RimSort misreads packageIds if there are more than 3 dots "."

### ISSUE THREAD

**Issue by Raizanad** [RimSort/RimSort#477]
**Describe the bug:**

If you try to add a rule for a mod that should be loaded after:
carolusclen.dlc.wmbp
carolusclen.dlc.wmbp.a
carolusclen.dlc.wmbp.b
Then rimsort will believe a and b are different, but wmbp is already in the ruleset.

**To Reproduce:**

Add these mods:
World Map Beautification Project - for Alpha Biomes
World Map Beautification Project - for More Biomes
Then try to add a rule for another mod that makes it load it after them. RimSort will say the mod is already on the list.

**Screenshots:**
![image](https://github.com/RimSort/RimSort/assets/131222736/681c9b8a-e8b5-47d5-b7d9-ae624af3a8aa)

**Comment by oceancabbage** [comment]
I was able to reproduce this by adding WMBP More Vanilla Biomes `carolusclen.dlc.wmbp.mvb` first, and then WMBP Alpha Biomes `carolusclen.dlc.wmbp`. Issue is happening because of a bug in equivalence checking (we're checking for substring rather than equivalence). Fix in https://github.com/RimSort/RimSort/pull/495

**Comment by Raizanad** [comment]
Great.
