### ISSUE TITLE
FIXME: Error after trying to set up SteamCMD

### ISSUE THREAD

**Issue by iambastian** [RimSort/RimSort#485]
**Describe the bug:**
After trying to set up SteamCMD, I got an exception which I didn't save and RimSort crashed. Trying to start it will throw following error and the app closes directly:

```
Traceback (most recent call last):
  File "C:\Tools\RimSort\__main__.py", line 112, in main_thread
  File "C:\Tools\RimSort\app\controllers\app_controller.py", line 42, in __init__
  File "C:\Tools\RimSort\app\controllers\settings_controller.py", line 58, in __init__
  File "C:\Tools\RimSort\app\controllers\settings_controller.py", line 461, in _update_view_from_model
TypeError: 'PySide6.QtWidgets.QAbstractButton.setChecked' called with wrong argument types:
  PySide6.QtWidgets.QAbstractButton.setChecked(NoneType)
Supported signatures:
  PySide6.QtWidgets.QAbstractButton.setChecked(bool)
```

I was looking into the code, but I'm not proficient in Python. I just can see, that the current value from `"steam_client_integration"` is not a boolean?!

Where are settings persisted? Deleting RimSort and redownloading & extracting won't solve the issue.

**To Reproduce:**
Not sure, what exactly I was doing to get this error. The app wanted to set up SteamCMD, but said, that the current path was wrong.

**Expected behavior:**
RimSort starts.

**Screenshots:**
![image](https://github.com/user-attachments/assets/ba711b94-5673-4332-b4a5-22d4c8cf7c2d)

**Please complete the following information:**

- Operating System: Win10
- Processor Architecture: x86
- RimSort version: 1.0.8
- Please provide a `RimSort.log`: Can't find any log file
- Are you running from the Python interpreter or from a compiled RimSort release? compiled release
- If this is a sorting issue, what sort mode are you using?: -

**Additional context:**
-

**Comment by hk21702** [comment]
What version are you using?

Also, it might have already been overwritten by now, but at least for future reference, you can upload the log file by going to `file > upload log`. There are two options, one will upload the log file for the current session, the other from the previous. 

What your error looks like is that something went wrong when saving the settings file that RimSort makes, and its corrupted now. On windows, the path to the file should be `AppData/Local/RimSort/` and you'll find a settings.json file there. (Your logs are also there too btw).

Delete that and then restart RimSort so that it regenerates. Note that this will reset your settings. You can open it and try and see if you can fix it yourself but my guess is that something happened when writing that caused the issue and its just cut off.

**Comment by LionelColaso** [comment]
@iambastian since you are using version 1.0.8 can you try Edge version 1.0.9 shoiuld fix your issue

**Comment by hk21702** [comment]
Oh yes. I think this may be a known issue for 1.0.8 involving initial setup. The crash on load is incidental due to the settings file being corrupted somewhat.

Try the latest edge version, though it is likely that you may still need to delete your settings file.

**Comment by iambastian** [comment]
Oh, I tried the edge version and it starts then. For me it looks like the edge version created a new temporary array in the settings.json in `instances` which was called "somewhat-1.5". After saving the settings in the client, the array was persisted in `instances.Default`.

So there was no need to delete the settings.json. Do you recommend that I stay on the edge version for now or should I downgrade to the stable rel?

Thank you both for your quick help!

**Comment by hk21702** [comment]
I would stay on the edge version for now. There's several fixes there that are no present in the latest stable release. We're most likely going to look to bump the stable release within a week anyways.

I'm going to close this for now since it seems resolved. If not, feel free to reopen.
