### ISSUE TITLE
Suggestion: Delete/Archive PNG textures

### ISSUE THREAD

**Issue by jomar0** [RimSort/RimSort#498]
I am not sure that the game actually does this, but I know that the engine loads all the mods into memory prior before the main menu. When converting PNG textures to DDS, does the engine load both versions of the texture? If so, is it possible for RimSort to delete/archive the PNG textures to reduce the loading time of the game and compress the mods folder?

**Comment by Raizanad** [comment]
So, personally I like this idea... But I'll be honest as a "lurker" on RimSort development, this may take a while, and maybe the game load won't benefit at all but there is a benefit for you on disk space.

I would try submitting the request directly in the github of todds, the developer recently dropped adding new features due to real life but you may try anyway.

As for an actually practical solution right now, I recommend you install "everything" which is an indexer for windows, then do a quick png filtering after you have your dds files. Everything can skip the some subfolders if you set the proper search parameters, like skipping every preview.png and modicon.png since the former needs to be png for rimsort and isn't duplicated by todds, and modicon I'm uncertain.

**Comment by twstagg** [comment]
This is not something I think we should support in RimSort. It messes with Steam{cmd}'s ability to update the mods from a depot without validation. Also, the game will not use the png textures in memory if you are using a .dds texture mod to load your .dds variants instead.

Feel free to write a script or something of your own to facilitate this.
