### ISSUE TITLE
FIXME: Segfault on Ubuntu 22.04

### ISSUE THREAD

**Issue by memebr1nger** [RimSort/RimSort#553]
**Describe the bug:**
Got a segfault when trying to start the program from 1.0.9 release. 

* Ubuntu (Xubuntu) 22.04
* Arch: x64
* RimSort version: 1.0.9
* Rimsort.log is empty
* RimSort-v1.0.9-Ubuntu-22.04_x86_64

Here is the dump file:
[dump.zip](https://github.com/user-attachments/files/16532773/dump.zip)

**Comment by hk21702** [comment]
Have you tried redownloading the program? Sometimes, in rare crash cases where it's a crash on startup before logs start, and it's a memory access issue, the download got corrupted at some point.

**Comment by hk21702** [comment]
Out of curiosity, do previous versions or the current edge version work? If not, it might be that you're missing shared libraries that Qt needs. https://doc.qt.io/qt-6/linux-requirements.html

If those all previous versions work but not 1.0.9 or edge then its prob an issue with our compiler or something deeper.

I haven't had time to look at the dump but I'll try to get to that

**Comment by memebr1nger** [comment]
Version 1.0.7 works, next versions give a segfault.

**Comment by hk21702** [comment]
Just to confirm, 1.0.8, 1.0.9, and latest edge all give seg faults right? 1.0.7 does not? If so that is rather strange as 1.0.8 did not have major changes from 1.0.7. There were some dependency bumps but nothing related to the build pipeline. 

Are you able to run the non-compiled version? Ie, cloning the repo and then just running RimSort via a python interpreter? It's okay if you don't know how/don't want to do this. 

Looking at the dump, the seg fault happens within vfscanf-internal.c, which is scanf, a function in c. Thing is, RimSort on the development side is all Python. Nuikta does compile it so there could be something messing it around here, but I haven't seen this issue with anyone else, let alone across multiple versions.

There are a few other lines when loading the dump file that make me suspect something is up with your system's shared libraries. Just to confirm it's not because I'm loading your dump file on my machine, do me a favor and load your dump file in gdb for me. Please let me know if there are any warnings about a dynamic section for a lib not being at the expected address. If there is something there, please leave a screenshot of that. 

If it really is related to those libs, most likely if I had to guess is that it's a version mismatch of some sort. You can then try updating your system and maybe potentially re-installing those libs specifically.

**Comment by memebr1nger** [comment]
Yes, 1.0.8, 1.0.9 and edge give segfault.
After your reply I ran Rimsort via python and it worked:
![image_2024-08-09_13-01-19](https://github.com/user-attachments/assets/3bcc25b5-5f56-41dc-aca8-9d57a4e66fa9)

Gdb output when trying to run from 1.0.9 release:
```
$ gdb -c core-RimSort.18024.r2d2.1723195530
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
[New LWP 18024]

warning: Section `.reg-xstate/18024' in core file too small.
Core was generated by `./RimSort'.
Program terminated with signal SIGABRT, Aborted.

warning: Section `.reg-xstate/18024' in core file too small.
#0  0x00007f802b0a19fc in ?? ()
(gdb) bt
#0  0x00007f802b0a19fc in ?? ()
#1  0x00007ffc35ed4a16 in ?? ()
#2  0x00007f802b0de2ad in ?? ()
#3  0x0000000000000000 in ?? ()
```

And a new dump just in case:
[new_dump.zip](https://github.com/user-attachments/files/16559902/new_dump.zip)

Thanks for the replies and for the help btw.

**Comment by hk21702** [comment]
Well at least we've confirmed it's the compiled releases. The result of that gdb response is unfortunately not the most useful. Can you give me your version of gdb and also run a bcaktrace with it?

**Comment by memebr1nger** [comment]
My previous post contains both the version and the backtrace output:
```
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04.2) 12.1
```
```
(gdb) bt
#0  0x00007f802b0a19fc in ?? ()
#1  0x00007ffc35ed4a16 in ?? ()
#2  0x00007f802b0de2ad in ?? ()
#3  0x0000000000000000 in ?? ()
```
Unfortunately I don't know where to get the debug symbols from.

**Comment by hk21702** [comment]
Woops. Don't know how I managed to miss that.

As for what to do with this trace, I'm pretty stumped. Most I can tell you to do at this point is make sure your system is updated, you have all the shared system libraries needed and that those are updated as well. There is a potential that a nuitka update somewhere broke something between 1.0.7 and 1.0.8 but thats fairly unlikely.

**Comment by hk21702** [comment]
Looking at this a bit further, I somehow missed that you were using Xubuntu. Xubuntu while a flavor of Ubuntu, is not what our runners are compiling for. We just use the Ubuntu runners that GitHub provides. The default desktop environment is different, and given that RimSort is a GUI app, that is likely causing issues here, especially since RimSort seems to work on Xubuntu when ran from the Python interpreter.

You'll likely just need to run from interp, or build/compile yourself. Instructions for doing both of these things are in the wiki.
